---

- name: apt initial update
  command:
    /usr/bin/apt-get update -y
  tags: init

- name: apt initial upgrade
  command:
    /usr/bin/apt-get upgrade -y
  tags: init

- name: install python-apt
  command:
    /usr/bin/apt-get install python-apt -y
  tags: init

- name: add ll alias
  lineinfile:
    dest=/etc/profile
    regexp='^alias ll'
    insertafter=EOF
    line='alias ll="ls -aul"'
    state=present
  tags: init

- name: install some packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - openjdk-7-jdk
    - emacs
    - tmux
  tags: init

- name: remove some packages
  apt:
    pkg={{ item }}
    state=absent
    purge=yes
  with_items:
    - oracle-java7-jdk
    - wolfram-engine
  tags: init

- name: install packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - hostapd
    - isc-dhcp-server
  tags: init

- name: network nat rules configuration
  template:
    src=etc_iptables.ipv4.nat.j2
    dest=/etc/iptables.ipv4.nat
    mode=0644
    owner=root
    group=root
  tags: conf

- name: network interfaces configuration
  template:
    src=etc_network_interfaces.j2
    dest=/etc/network/interfaces
    mode=0644
    owner=root
    group=root
  tags: conf

- name: dhcpd subnet configuration
  template:
    src=etc_dhcp_dhcpd.conf.j2
    dest=/etc/dhcp/dhcpd.conf
    mode=0644
    owner=root
    group=root
  notify: restart dhcpd
  tags: conf

- name: dhcpd interface configuration
  template:
    src=etc_default_isc-dhcp-server.j2
    dest=/etc/default/isc-dhcp-server
    mode=0644
    owner=root
    group=root
  notify: restart dhcpd
  tags: conf

- name: hostapd configuration
  template:
    src=etc_hostapd_hostapd.conf.j2
    dest=/etc/hostapd/hostapd.conf
    mode=0644
    owner=root
    group=root
  notify: restart hostapd
  tags: conf

- name: hostapd configuration pointer
  template:
    src=etc_default_hostapd.j2
    dest=/etc/default/hostapd
    mode=0644
    owner=root
    group=root
  notify: restart hostapd
  tags: conf

- name: enable ipv4 forward
  lineinfile:
    dest=/etc/sysctl.conf
    regexp='^net.ipv4.ip_forward=1$'
    state=present
    line='net.ipv4.ip_forward=1'
    insertafter=EOF
  tags: conf

- name: enable and start services
  service:
    name={{ item }}
    state=started
    enabled=yes
  with_items:
    - hostapd
    - isc-dhcp-server
  tags: conf
