---
- name: apt initial update
  command:
    /usr/bin/apt-get update
  tags: init

- name: install python-apt
  command:
    /usr/bin/apt-get install python-apt -y
  tags: init

- name: ntp
  apt:
    pkg={{item}}
    state=present
  with_items:
    - ntp
    - ntpdate
  notify:
    - restart ntp
  tags: init

- name: add ll alias
  lineinfile:
    dest=/etc/profile
    regexp='^alias ll'
    insertafter=EOF
    line='alias ll="ls -aul"'
    state=present
  tags: init

- name: blacklist kernel module pn533
  lineinfile:
    dest=/etc/modprobe.d/nfc-blacklist.conf
    regexp='^blacklist pn533'
    insertafter=EOF
    line='blacklist pn533'
    state=present
    create=yes
  tags: init

- name: blacklist kernel module nfc
  lineinfile:
    dest=/etc/modprobe.d/nfc-blacklist.conf
    regexp='^blacklist nfc'
    insertafter=EOF
    line='blacklist nfc'
    state=present
    create=yes
  tags: init

- name: enable kernel module i2c-bcm2708
  lineinfile:
    dest=/etc/modules
    regexp='^i2c-bcm2708'
    insertafter=EOF
    line='i2c-bcm2708'
    state=present
  tags: init

- name: enable kernel module i2c-dev
  lineinfile:
    dest=/etc/modules
    regexp='^i2c-dev'
    insertafter=EOF
    line='i2c-dev'
    state=present
  tags: init

- name: install useful packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - pcscd
    - libacsccid1
    - emacs
    - openjdk-7-jdk
    - tmux
  tags: init

- name: remove useless packages
  apt:
    pkg={{ item }}
    state=absent
    purge=yes
  with_items:
    - oracle-java7-jdk
    - wolfram-engine
    - libccid
  tags: init
